name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.19', '1.20', '1.21' ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Install dependencies
      run: go get .
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Build binary
      run: |
        GOOS=linux GOARCH=amd64 go build -o ./bin/enshunter-linux-amd64
        GOOS=darwin GOARCH=amd64 go build -o ./bin/enshunter-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build -o ./bin/enshunter-darwin-arm64
        GOOS=windows GOARCH=amd64 go build -o ./bin/enshunter-windows-amd64.exe
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./bin/enshunter-linux-amd64
          ./bin/enshunter-darwin-amd64
          ./bin/enshunter-darwin-arm64
          ./bin/enshunter-windows-amd64.exe
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
